[phases.build]
cmds = ["npm install -g @imputnet/bgutil-yt-dlp-pot-provider"]
[start]
cmd = "bash start.sh"
[phases.setup]
nixPkgs = ["ffmpeg", "nodejs_20"]

[phases.build]
cmds = ["npm install -g @imputnet/bgutil-yt-dlp-pot-provider"]
